# Generated by Django 4.2.3 on 2023-07-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('storage', '0002_alter_storage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
    ]
