# Generated by Django 4.2.3 on 2023-07-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This product already exists in storage.'}, max_length=30, unique=True, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
                ('description_short', models.TextField(verbose_name='description short')),
                ('description_long', models.TextField(verbose_name='description long')),
                ('image', models.ImageField(upload_to='products', verbose_name='image')),
                ('size', models.CharField(max_length=10, verbose_name='size')),
                ('brand', models.CharField(max_length=20, verbose_name='brand')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='discount price')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
