# Generated by Django 4.2.3 on 2023-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This product already exists in storage.'}, max_length=30, unique=True, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='products', verbose_name='image')),
                ('size', models.CharField(max_length=10, verbose_name='size')),
                ('brand', models.CharField(max_length=20, verbose_name='brand')),
            ],
        ),
    ]
