# Generated by Django 4.2.3 on 2023-07-29 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=512, verbose_name='Street/Avenue')),
                ('number', models.CharField(max_length=16, verbose_name='Number')),
                ('extra', models.CharField(max_length=64, verbose_name='Extra')),
                ('neighborhood', models.CharField(max_length=64, verbose_name='Neighborhood')),
                ('city', models.CharField(max_length=256, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=8, verbose_name='Zip code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
