# Generated by Django 4.2.3 on 2023-07-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=512, verbose_name='street/avenue')),
                ('number', models.CharField(max_length=16, verbose_name='number')),
                ('extra', models.CharField(max_length=64, verbose_name='extra')),
                ('neighborhood', models.CharField(max_length=64, verbose_name='neighborhood')),
                ('city', models.CharField(max_length=256, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=8, verbose_name='zip code')),
            ],
        ),
    ]
